namespace InternetClawMachine.Games.GameHelpers
{
    public enum ClawDirection
    {
        NA,
        FORWARD,
        BACKWARD,
        LEFT,
        RIGHT,
        UP,
        DOWN,
        STOP,
        DOWN1,
        DOWN2,
        DOWN3,
        DOWN4,
        NONE,
        HIT,
        HITSHORT,
        FORWARD_SHORT,
        BACKWARD_SHORT,
        LEFT_SHORT,
        RIGHT_SHORT,
        FREEMOVE,
        FREEMOVESMALL,
        ROTATE,
        COUNTERHIT,
        COUNTERHITSHORT
    }
}